### ISSUE TITLE
How to accelerate the HHBLITS step with GPU

### ISSUE THREAD

**Issue by Licko0909** [Zuricho/ParallelFold#1]
Halo! Thanks for your good job! I have some question about this job:

Q1: Do you Know how to accelerate the HHBLITS step with GPU？
![image](https://user-images.githubusercontent.com/27897166/130094349-0eadc750-e939-4915-918a-070b8136f393.png)

Q2: I use `--cpu 8`  to run jackhmmer but alway just use 2 cpu and I dont know why

![image](https://user-images.githubusercontent.com/27897166/130094402-9409db80-b750-42c0-9adb-9e5477feee6e.png)

**Comment by Zuricho** [comment]
Actually we are not sure about whether GPU can accelerate HHblits, and I think it couldn't. Different speed of using GPU node and CPU node may be different in many ways like its memory, loading files or submitting plenty tasks. JackHMMER did not use that much of CPUs, and it's kind of complicated for things like these MSA algorithms. We are working on this currently, maybe we will find an optimal solution soon.

**Comment by johnds123** [comment]
HHblits can be built for MPI. This might help to gain better I/O performance when threads are executed on different systems.

**Comment by Licko0909** [comment]
Thanks you!!!

**Comment by Licko0909** [comment]
> 
Thanks you!!!

**Comment by Licko0909** [comment]
> HHblits can be built for MPI. This might help to gain better I/O performance when threads are executed on different systems.

Thanks you!!!

**Comment by Licko0909** [comment]
> Actually we are not sure about whether GPU can accelerate HHblits, and I think it couldn't. Different speed of using GPU node and CPU node may be different in many ways like its memory, loading files or submitting plenty tasks. JackHMMER did not use that much of CPUs, and it's kind of complicated for things like these MSA algorithms. We are working on this currently, maybe we will find an optimal solution soon.

Thanks you!!!
