### ISSUE TITLE
How to run GPU part?

### ISSUE THREAD

**Issue by hrzolix** [Zuricho/ParallelFold#10]
How do I run model inference on GPU part of the process after featurization step?
Does the model inference step automatically find feature.pkl in some folder?

**Comment by Zuricho** [comment]
You're right, `run_alphafold.py` without feature flag will automatically find `feature.pkl` in `output` folder, if `feature.pkl` exists, it will skip featurization step.

**Comment by hrzolix** [comment]
So basically I ran this:
`run_alphafold.sh -d $ALPHAFOLDDB -o test_parafold -m model_1 -i example/query.fasta -p monomer_ptm -f -g False`
and i got the .pkl file and msas folder, that was on the featurization CPU part.
 Now I wanna do the GPU part so will this work? Or something else is required?
`run_alphafold.sh -d $ALPHAFOLDDB -o test_parafold -m model_1 -i example/query.fasta -p monomer_ptm -t 2021-12-10 -l`

Sorry if I'm asking something obvious, just trying to understand how this works.

**Comment by Zuricho** [comment]
you don't need to use `-l`, others were right

**Comment by hrzolix** [comment]
Thank you for your quick response
