### ISSUE TITLE
ValueError: jaxlib is version 0.1.69, but this version of jax requires version 0.1.74.

### ISSUE THREAD

**Issue by chenshixinnb** [Zuricho/ParallelFold#13]
根据您的步骤安装conda环境，
在conda环境中执行：import jax; print(jax.devices())
报错：ValueError: jaxlib is version 0.1.69, but this version of jax requires version 0.1.74.
请问如何解决呢，谢谢！

**Comment by chenshixinnb** [comment]
#conda list |grep jax
jax                       0.2.26                   pypi_0    pypi
jaxlib                    0.1.69+cuda101           pypi_0    pypi

**Comment by Zuricho** [comment]
装一下低版本的jax好一点，pip install jax==0.2.14 降低一下版本试试？

**Comment by chenshixinnb** [comment]
可以了，非常感谢！
