### ISSUE TITLE
Where Can I find The Protein sequence？

### ISSUE THREAD

**Issue by yanchenmochen** [Zuricho/ParallelFold#25]
After Reading the Article, AlphaFold Deployment and Optimization on HPC Platform， I want make some experiments according to the arctile, But I cannot find the Protein sequence online. Can you tell me the way to downloading the fasta file in the article?

**Comment by Zuricho** [comment]
Could you specify which protein sequence, is the miniprotein test set?

**Comment by yanchenmochen** [comment]
I donot know whether it is miniprotein test set or not, I means the protein sequence in the article, for example, CasF1, VaIL-497AA, NCGpS-497AA, T1024_1, T1024_2， histone_1. I want try the same sequences as mentioned in the article.

**Comment by Zuricho** [comment]
I will upload a file for that soon

**Comment by yanchenmochen** [comment]
> I will upload a file for that soon
Appreciate your answer。 Now I just find some fasta file of varing length on CASP14 web。It is ok too.
