### ISSUE TITLE
运行脚本后，还是有问题。

### ISSUE THREAD

**Issue by zhoujingyu13687306871** [Zuricho/ParallelFold#3]
博士好！
我发现我运行脚本后，cpu部分是可以正常运行了，但是GPU部分不管短序列（200+aa）还是长序列（1800+aa），都会报错，我的脚本如下：
#!/bin/bash
module load anaconda/2020.11
source activate /data/home/zhoujy/run/alphafold2
./run_feature.sh -d /data/public/alphafold2 -o /data/home/zhoujy/run/output -m model_1 -f /data/home/zhoujy/run/input/Q9NYP9.fasta -t 2021-07-27
./run_alphafold.sh -d /data/public/alphafold2 -o /data/home/zhoujy/run/output -m model_1,model_2,model_3,model_4,model_5 -f /data/home/zhoujy/run/input/Q9NYP9.fasta -t 2021-07-27

用了1张GPU卡提交的。

报错内容如下：

 87 I0927 17:05:14.162350 139818804778816 xla_bridge.py:226] Unable to initialize backend 'tpu': Invalid argument: TpuPlatform is not available.
 88 I0927 17:05:23.883118 139818804778816 run_alphafold.py:272] Have 5 models: ['model_1', 'model_2', 'model_3', 'model_4', 'model_5']
 89 I0927 17:05:23.883379 139818804778816 run_alphafold.py:285] Using random seed 491376288278862761 for the data pipeline
 90 I0927 17:05:23.892619 139818804778816 run_alphafold.py:151] Running model model_1
 91 I0927 17:05:34.480318 139818804778816 model.py:131] Running predict with shape(feat) = {'aatype': (4, 233), 'residue_index': (4, 233), 'seq_length': (4,)    , 'template_aatype': (4, 4, 233), 'template_all_atom_masks': (4, 4, 233, 37), 'template_all_atom_positions': (4, 4, 233, 37, 3), 'template_sum_probs': (4    , 4, 1), 'is_distillation': (4,), 'seq_mask': (4, 233), 'msa_mask': (4, 508, 233), 'msa_row_mask': (4, 508), 'random_crop_to_size_seed': (4, 2), 'templat    e_mask': (4, 4), 'template_pseudo_beta': (4, 4, 233, 3), 'template_pseudo_beta_mask': (4, 4, 233), 'atom14_atom_exists': (4, 233, 14), 'residx_atom14_to_    atom37': (4, 233, 14), 'residx_atom37_to_atom14': (4, 233, 37), 'atom37_atom_exists': (4, 233, 37), 'extra_msa': (4, 5120, 233), 'extra_msa_mask': (4, 51    20, 233), 'extra_msa_row_mask': (4, 5120), 'bert_mask': (4, 508, 233), 'true_msa': (4, 508, 233), 'extra_has_deletion': (4, 5120, 233), 'extra_deletion_v    alue': (4, 5120, 233), 'msa_feat': (4, 508, 233, 49), 'target_feat': (4, 233, 22)}
 92 2021-09-27 17:05:35.143686: W external/org_tensorflow/tensorflow/stream_executor/gpu/asm_compiler.cc:81] Couldn't get ptxas version string: Internal: Run    ning ptxas --version returned 32512
 93 2021-09-27 17:05:35.324896: F external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:479] ptxas returned an error during compilati    on of ptx to sass: 'Internal: ptxas exited with non-zero error code 32512, output: '  If the error message indicates that a file could not be written, pl    ease verify that sufficient filesystem space is provided.
 94 Fatal Python error: Aborted
 95
 96 Thread 0x00007f2a1a311740 (most recent call first):
 97   File "/data/home/zhoujy/run/alphafold2/lib/python3.8/site-packages/jax/interpreters/xla.py", line 387 in backend_compile
 98   File "/data/home/zhoujy/run/alphafold2/lib/python3.8/site-packages/jax/interpreters/xla.py", line 324 in xla_primitive_callable
 99   File "/data/home/zhoujy/run/alphafold2/lib/python3.8/site-packages/jax/_src/util.py", line 188 in cached
100   File "/data/home/zhoujy/run/alphafold2/lib/python3.8/site-packages/jax/_src/util.py", line 195 in wrapper
101   File "/data/home/zhoujy/run/alphafold2/lib/python3.8/site-packages/jax/interpreters/xla.py", line 275 in apply_primitive
102   File "/data/home/zhoujy/run/alphafold2/lib/python3.8/site-packages/jax/core.py", line 612 in process_primitive
103   File "/data/home/zhoujy/run/alphafold2/lib/python3.8/site-packages/jax/core.py", line 267 in bind
104   File "/data/home/zhoujy/run/alphafold2/lib/python3.8/site-packages/jax/_src/lax/lax.py", line 388 in shift_right_logical
105   File "/data/home/zhoujy/run/alphafold2/lib/python3.8/site-packages/jax/_src/prng.py", line 229 in threefry_seed
106   File "/data/home/zhoujy/run/alphafold2/lib/python3.8/site-packages/jax/_src/prng.py", line 191 in seed_with_impl
107   File "/data/home/zhoujy/run/alphafold2/lib/python3.8/site-packages/jax/_src/random.py", line 105 in PRNGKey
108   File "/data/run01/zhoujy/ParallelFold-main/alphafold/model/model.py", line 133 in predict
109   File "/data/run01/zhoujy/ParallelFold-main/run_alphafold.py", line 158 in predict_structure
110   File "/data/run01/zhoujy/ParallelFold-main/run_alphafold.py", line 289 in main
111   File "/data/home/zhoujy/.local/lib/python3.8/site-packages/absl/app.py", line 258 in _run_main
112   File "/data/home/zhoujy/.local/lib/python3.8/site-packages/absl/app.py", line 312 in run
113   File "/data/run01/zhoujy/ParallelFold-main/run_alphafold.py", line 316 in <module>

从92-113行，不论序列长短都会出现这种报错。这是什么原因引起的呢？ @Zuricho

**Comment by Zuricho** [comment]
我之前也遇到过ptxas报错，这个原因一般是cuda版本和jax版本无法对应导致的。你需要检查你的cuda版本、cuda driver版本，已经jax版本的对应关系，现在jaxlib 0.1.70已经不支持cuda 10.1，所以在我的安装代码中已经将其降级到了1.69的版本，建议你根据需要对应jax版本

**Comment by zhoujingyu13687306871** [comment]
> 我当时按照教程安装的时候，发现jax版本是0.2.14，而jaxlib是0.16.9cuda101版本，是不是说，我需要将jax降到0.16.9吗？另外我在运行脚本时候发现，cpu部分没有达到预期中的三个程序一起并行计算，先是Jackhmmer、HHsearch、HHblits顺序运行的，貌似跟官网的运行模式是一样的。

@Zuricho

**Comment by Zuricho** [comment]
CPU 并行的脚本我们还没放到github上，jax版本就是0.2.14，不需要降级，jaxlib才是0.16.9
你nvidia-smi得到的CUDA版本是多少啊

**Comment by zhoujingyu13687306871** [comment]
> CPU 并行的脚本我们还没放到github上，jax版本就是0.2.14，不需要降级，jaxlib才是0.16.9
> 你nvidia-smi得到的CUDA版本是多少啊

Every 0.1s: nvidia-smi                                                                                                               Tue Sep 28 13:14:13 2021

Tue Sep 28 13:14:13 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:00:0D.0 Off |                  Off |
| N/A   43C    P0    55W / 300W |   2318MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      8667      C   python                            479MiB |
+-----------------------------------------------------------------------------+

**Comment by zhoujingyu13687306871** [comment]
博士，您方便将cpu并行的脚本发我邮箱吗？mrzhoujingyu@163.com  多谢了！ @Zuricho

**Comment by Zuricho** [comment]
> 博士，您方便将cpu并行的脚本发我邮箱吗？[mrzhoujingyu@163.com](mailto:mrzhoujingyu@163.com) 多谢了！ @Zuricho

CPU并行部分我们还没整理完，后面会放到GitHub上的；而且CPU并行对效果的提升并不必要，分拆CPU和GPU的意义反而更大

**Comment by zhoujingyu13687306871** [comment]
> > 博士，您方便将cpu并行的脚本发我邮箱吗？[mrzhoujingyu@163.com](mailto:mrzhoujingyu@163.com) 多谢了！ @Zuricho
> 
> CPU并行部分我们还没整理完，后面会放到GitHub上的；而且CPU并行对效果的提升并不必要，分拆CPU和GPU的意义反而更大

那请帮忙看看，我以上的脚本，这么写是可以的不？我的目的是计算完CPU部分后，紧接着算GPU部分。

**Comment by Zuricho** [comment]
> > > CPU 并行的脚本我们还没放到github上，jax版本就是0.2.14，不需要降级，jaxlib才是0.16.9
> > > 你nvidia-smi得到的CUDA版本是多少啊
> > 
> > 
> > Every 0.1s: nvidia-smi Tue Sep 28 13:14:13 2021
> > Tue Sep 28 13:14:13 2021
> > +-----------------------------------------------------------------------------+
> > | NVIDIA-SMI 460.32.03 Driver Version: 460.32.03 CUDA Version: 11.2 |
> > |-------------------------------+----------------------+----------------------+
> > | GPU Name Persistence-M| Bus-Id Disp.A | Volatile Uncorr. ECC |
> > | Fan Temp Perf Pwr:Usage/Cap| Memory-Usage | GPU-Util Compute M. |
> > | | | MIG M. |
> > |===============================+======================+======================|
> > | 0 Tesla V100-SXM2... On | 00000000:00:0D.0 Off | Off |
> > | N/A 43C P0 55W / 300W | 2318MiB / 32510MiB | 0% Default |
> > | | | N/A |
> > +-------------------------------+----------------------+----------------------+
> > +-----------------------------------------------------------------------------+
> > | Processes: |
> > | GPU GI CI PID Type Process name GPU Memory |
> > | ID ID Usage |
> > |=============================================================================|
> > | 0 N/A N/A 8667 C python 479MiB |
> > +-----------------------------------------------------------------------------+
> 
> 我这边在脚本里面额外加了cuda10.1环境变量，
> #!/bin/bash
> module load cudnn/7.6.5.32_cuda10.1
> module load anaconda/2020.11
> source activate /data/home/zhoujy/run/alphafold2
> ./run_feature.sh -d /data/public/alphafold2 -o /data/home/zhoujy/run/output -m model_1 -f /data/home/zhoujy/run/input/Q9NYP9.fasta -t 2021-07-27
> ./run_alphafold.sh -d /data/public/alphafold2 -o /data/home/zhoujy/run/output -m model_1,model_2,model_3,model_4,model_5 -f /data/home/zhoujy/run/input/Q9NYP9.fasta -t 2021-07-27

我感觉你可以不走我的方案，直接装jax，然后jaxlib的时候更新到cuda=112，装cudatoolkit的时候选11.2，cudnn是8.0.4的版本；如果在python中安装了cudatoolkit，就不需要本地的cuda；TensorFlow选择2.5.0版本
这个例子是在cuda11版本上装的，python环境可以参考一些 https://github.com/kuixu/alphafold

**Comment by Zuricho** [comment]
> > > 博士，您方便将cpu并行的脚本发我邮箱吗？[mrzhoujingyu@163.com](mailto:mrzhoujingyu@163.com) 多谢了！ @Zuricho
> > 
> > 
> > CPU并行部分我们还没整理完，后面会放到GitHub上的；而且CPU并行对效果的提升并不必要，分拆CPU和GPU的意义反而更大
> 
> 那请帮忙看看，我以上的脚本，这么写是可以的不？我的目的是计算完CPU部分后，紧接着算GPU部分。

这完全没必要用ParallelFold，其实直接AlphaFold官方给的流程就是先CPU再GPU，而且我的run_alphafold.sh如果直接跑，没有MSA的结果的话它会自动识别到这个情况，自己跑CPU部分的
也就是说，如果你要一次完成一个任务，用run_alphafold.sh就足够了

**Comment by Zuricho** [comment]
> f

而且你的-f后面有回车，这是错误的，执行命令只有一行

**Comment by zhoujingyu13687306871** [comment]
> > f
> 
> 而且你的-f后面有回车，这是错误的，执行命令只有一行

没有呢，这是复制粘贴的正常换行，我脚本里面是写在同一行的。

**Comment by zhoujingyu13687306871** [comment]
> > > > 博士，您方便将cpu并行的脚本发我邮箱吗？[mrzhoujingyu@163.com](mailto:mrzhoujingyu@163.com) 多谢了！ @Zuricho
> > > 
> > > 
> > > CPU并行部分我们还没整理完，后面会放到GitHub上的；而且CPU并行对效果的提升并不必要，分拆CPU和GPU的意义反而更大
> > 
> > 
> > 那请帮忙看看，我以上的脚本，这么写是可以的不？我的目的是计算完CPU部分后，紧接着算GPU部分。
> 
> 这完全没必要用ParallelFold，其实直接AlphaFold官方给的流程就是先CPU再GPU，而且我的run_alphafold.sh如果直接跑，没有MSA的结果的话它会自动识别到这个情况，自己跑CPU部分的
> 也就是说，如果你要一次完成一个任务，用run_alphafold.sh就足够了

原来是这样，我懂了。意思就是说，如果之前跑cpu的时候，在output里面出现了feature.pkl文件，那么run_alphafold.sh会识别到，就从GPU部分开始跑了，避开cpu部分，节省时间。

**Comment by Zuricho** [comment]
> > > > > 博士，您方便将cpu并行的脚本发我邮箱吗？[mrzhoujingyu@163.com](mailto:mrzhoujingyu@163.com) 多谢了！ @Zuricho
> > > > 
> > > > 
> > > > CPU并行部分我们还没整理完，后面会放到GitHub上的；而且CPU并行对效果的提升并不必要，分拆CPU和GPU的意义反而更大
> > > 
> > > 
> > > 那请帮忙看看，我以上的脚本，这么写是可以的不？我的目的是计算完CPU部分后，紧接着算GPU部分。
> > 
> > 
> > 这完全没必要用ParallelFold，其实直接AlphaFold官方给的流程就是先CPU再GPU，而且我的run_alphafold.sh如果直接跑，没有MSA的结果的话它会自动识别到这个情况，自己跑CPU部分的
> > 也就是说，如果你要一次完成一个任务，用run_alphafold.sh就足够了
> 
> 原来是这样，我懂了。意思就是说，如果之前跑cpu的时候，在output里面出现了feature.pkl文件，那么run_alphafold.sh会识别到，就从GPU部分开始跑了，避开cpu部分，节省时间。

bingo，就是这个意思

**Comment by zhoujingyu13687306871** [comment]
> > > > > > 博士，您方便将cpu并行的脚本发我邮箱吗？[mrzhoujingyu@163.com](mailto:mrzhoujingyu@163.com) 多谢了！ @Zuricho
> > > > > 
> > > > > 
> > > > > CPU并行部分我们还没整理完，后面会放到GitHub上的；而且CPU并行对效果的提升并不必要，分拆CPU和GPU的意义反而更大
> > > > 
> > > > 
> > > > 那请帮忙看看，我以上的脚本，这么写是可以的不？我的目的是计算完CPU部分后，紧接着算GPU部分。
> > > 
> > > 
> > > 这完全没必要用ParallelFold，其实直接AlphaFold官方给的流程就是先CPU再GPU，而且我的run_alphafold.sh如果直接跑，没有MSA的结果的话它会自动识别到这个情况，自己跑CPU部分的
> > > 也就是说，如果你要一次完成一个任务，用run_alphafold.sh就足够了
> > 
> > 
> > 原来是这样，我懂了。意思就是说，如果之前跑cpu的时候，在output里面出现了feature.pkl文件，那么run_alphafold.sh会识别到，就从GPU部分开始跑了，避开cpu部分，节省时间。
> 
> bingo，就是这个意思

好的，期待你的后续工作。

**Comment by zhoujingyu13687306871** [comment]
博士好！我昨天进行多次尝试后，现在可以运行了，但是我发现运行run_alphafold.sh脚本的时候，涉及GPU计算部分，在相当长的一段时间处于CPU运行状态，GPU一动不动，如下图所示，这个是否正常呢？另外前面在安装tensorflow阶段，是否有必要安装GPU版的tensorflow呢？

<img width="960" alt="企业微信截图_1632907186779" src="https://user-images.githubusercontent.com/47057417/135241571-299ea7b4-e391-4a3d-ba58-9726b6eefde5.png">
