### ISSUE TITLE
`run_alphafold.sh` on fresh Linux install has "bad interpreter" error

### ISSUE THREAD

**Issue by cerebis** [Zuricho/ParallelFold#31]
The bash script run_alphafold.sh seems to have MS-DOS end of line "\r\n", which is causing my Linux distro to object.

'''
-bash: ./run_alphafold.sh: /bin/bash^M: bad interpreter: No such file or directory
'''

Installed bash: version 4.4.20-4

Running dos2unix on the file resolves the issue.

**Comment by Zuricho** [comment]
Thanks, I will update a fixed version.

**Comment by cerebis** [comment]
I spoke too early. This seems to affect all the files in `scripts` as well.
