### ISSUE TITLE
openmm not found

### ISSUE THREAD

**Issue by NielsBDS** [Zuricho/ParallelFold#36]
Hi I tried loading all dependencies but I am getting an error stating that openmm cannot be found. Any idea how to resolve this?

[niedan@g-12-l0002 ~]$ module load alphafold/2.3.1
[niedan@g-12-l0002 ~]$ module load parallelfold/20230321
[niedan@g-12-l0002 ~]$
[niedan@g-12-l0002 ~]$ i=0
[niedan@g-12-l0002 ~]$ ### Get gene and fasta input file
[niedan@g-12-l0002 ~]$ cd /home/projects/ku_00012/data/niedan/alphafold/singlepass/screen/validation/IgSF/input/previous_reported
[niedan@g-12-l0002 previous_reported]$ files=( $(ls *.fasta) )
[niedan@g-12-l0002 previous_reported]$ filename=$(basename -- "${files[$i]}")
[niedan@g-12-l0002 previous_reported]$ gene="${filename%.*}"
[niedan@g-12-l0002 previous_reported]$ cd /home/projects/ku_00012/data/niedan/alphafold/singlepass/screen/logs
[niedan@g-12-l0002 logs]$
[niedan@g-12-l0002 logs]$ cd /services/tools/parallelfold/20230321
[niedan@g-12-l0002 20230321]$ bash ./run_alphafold.sh \
> -d /home/projects/ku_00012/data/niedan/alphafold/databases \
> -o /home/projects/ku_00012/data/niedan/alphafold/singlepass/screen/validation/IgSF/msas/previously_reported_v231 \
> -p multimer \
> -i "/home/projects/ku_00012/data/niedan/alphafold/singlepass/screen/validation/IgSF/input/previous_reported/${filename}" \
> -f false \
> -m model_1_multimer \
> -t 1800-01-01 \
> -c reduced_dbs \
> -use_gpu_relax=false
Traceback (most recent call last):
  File "/services/tools/parallelfold/20230321/run_alphafold.py", line 40, in <module>
    from alphafold.relax import relax
  File "/services/tools/parallelfold/20230321/alphafold/relax/relax.py", line 18, in <module>
    from alphafold.relax import amber_minimize
  File "/services/tools/parallelfold/20230321/alphafold/relax/amber_minimize.py", line 25, in <module>
    from alphafold.relax import cleanup
  File "/services/tools/parallelfold/20230321/alphafold/relax/cleanup.py", line 23, in <module>
    from openmm import app
ModuleNotFoundError: No module named 'openmm'
[niedan@g-12-l0002 20230321]$ conda list | grep openmm
openmm                    7.5.1            py39h71eca04_1    conda-forge

Thanks, 
Niels

**Comment by Zuricho** [comment]
Actually, I have update the installation guide to install openmm 7.7 rather than 7.5 (because the OpenMM developer said that they are not supporting OpenMM 7.5 anymore). I'm not so sure about where the openmm 7.5 came from. Maybe you can reinstall the conda environment again?
OpenMM 7.5 should be imported as `import simtk.openmm`, while OpenMM 7.7 is imported as `import openmm`, this is why your error comes from
