### ISSUE TITLE
GPU利用率问题

### ISSUE THREAD

**Issue by zhoujingyu13687306871** [Zuricho/ParallelFold#6]
博士好！我昨天进行多次尝试后，现在可以运行了，但是我发现运行run_alphafold.sh脚本的时候，涉及GPU计算部分，在相当长的一段时间处于CPU运行状态，GPU利用率长时间为0，我尝试计算一条序列长为2000的蛋白质，用了4个V100的卡，计算了9天，这个速度和情况这个是否正常呢？另外前面在安装tensorflow阶段，是否有必要安装GPU版的tensorflow呢？

@Zuricho

**Comment by Zuricho** [comment]
This is not right. Protein with 2000 should have less than 8 hours MSA and around 2 hour neural network inference (using GPU). I highly suspect your program didn't find your GPU and you should check whether it by using `print(jax.devices())`
